### PR TITLE
Reopening  PR #14

### LINKED ISSUE #13: Show pronite info on main page as well,,
Currently the pronite and chief guest banners are only visible on mobile website.. They are invisible on desktop. Show them on desktop as well and take care of responsiveness as well .

### PR DESCRIPTION
**Pull request by nimradium**
Making the Pronites banners visible on the desktop version and changing them to show as a slider
Fixes #13 
Reopening #14 
[Working repository](https://github.com/nimradium/Rann-Neeti-2018)

### CODE REVIEW

**Comment by nimradium** [comment]
I'm going to rework the slider soon so it looks better on smaller displays and with your approval I will add some arrows to the slider.

**Comment by dheeraj135** [comment]
@nimradium You should turn on github pages for your repository, so that one can easily verify changes you made.

**Comment by vsvipul** [comment]
nicely done.. i'll proceed to merge this to master :)

**Comment by vsvipul** [comment]
meanwhile, see if you can increase the poster size a bit in mobile devices..

**Comment by nimradium** [comment]
>meanwhile, see if you can increase the poster size a bit in mobile devices.. 

@vsvipul working on it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
