### PR TITLE
Showing pronite info on main page as well

### PR DESCRIPTION
**Pull request by nimradium**
Fixing #13

### CODE REVIEW

**Comment by vsvipul** [comment]
give working link of the repo when u submit a PR

**Comment by vsvipul** [comment]
i checked ur repo and the poster doesn't go so well with the page as they take a lot of space.. can you do a slider which makes us shuffle between the two and decrease the amount of size taken by the posters as well ? Basically, the posters should look good on desktop as they look on mobile. Currently, the are occupying a lot of space

**Comment by vsvipul** [comment]
i'll proceed to close this PR.. feel free to reopen the PR when u have made the required changes :+1:

**Comment by nimradium** [comment]
> i checked ur repo and the poster doesn't go so well with the page as they take a lot of space.. can you do a slider which makes us shuffle between the two and decrease the amount of size taken by the posters as well ? Basically, the posters should look good on desktop as they look on mobile. Currently, the are occupying a lot of space

working on it 👍

**Comment by vsvipul** [comment]
@nimradium  u can also try making 2 sections as in "Who we are" section and try showing both posters side by side, if that looks good. Just make sure, whatever u do, it looks good on the page..

**Pull request closed without merging**
