### PR TITLE
New Teampage #3

### LINKED ISSUE #3: Beautify team page
Make the team page more good looking ..

### PR DESCRIPTION
**Pull request by nimradium**
I added the new Team page with the main theme and stored the members in a json file so they can be modified easier.

PS: If you want some changes to be made, please don't close this PR and let me know so I can add these changes to this PR and don't have to open another PR.

Fixes #3 

++css/team/team_old.css:   
- css file for old team page

++ team.html:
- new team page

++ team.json:
- file including all team members

++ js/team.js:
- script to add the team members to the page

-- team.php:
- php doesn't work with github pages --> javascript

-- team.xml:
- json is easier to use with javascript than xml

Changes:

* css/team/team.css:
  * new CSS for team page
  * adding css for the category 
  * minor changes

* index.html:
  * bugfix

* team_old.html:
  * change to old css

* js/team.js:
  * adding support for category buttons

* team.html:
  * adding category buttons
  * minor changes

nimradium

github: https://github.com/nimradium
gitlab: https://gitlab.com/nimradium
WebLate: https://hosted.weblate.org/user/nimradium/
stackoverflow: https://stackoverflow.com/users/9688071/nimradium
Donations:
[](https://www.buymeacoffee.com/nimradium)

### CODE REVIEW

**Comment by vsvipul** [comment]
First of all i'd like to thank you personally for all the efforts you have put in for this PR. Only one thing missing is the categories view in mobile website of team page.. and the animations... you can skip the animations for now, but the categories in mobile website are very important. Do implement this if you can... I am keeping this PR open so you can make any required changed you want to. Good Luck. Hope you learned something from this PR.

**Comment by nimradium** [comment]
> First of all i'd like to thank you personally for all the efforts you have put in for this PR. Only one thing missing is the categories view in mobile website of team page.. and the animations... you can skip the animations for now, but the categories in mobile website are very important. Do implement this if you can... I am keeping this PR open so you can make any required changed you want to. Good Luck. Hope you learned something from this PR.

I've disabled the categories in mobile view because of responsiveness and it was disabled in the old page too but I'm going to change that. And for the animations I'm going to open a new Issue.

**Comment by vsvipul** [comment]
> I've disabled the categories in mobile view because of responsiveness and it was disabled in the old page too but I'm going to chan

it wasn't disabled in the old page.. you can see them by opening this in mobile view https://vsvipul.github.io/Rann-Neeti-2018/team.html and clicking on the top left button which opens up the categories.. You can try implementing the same in the new page too.. :)

**Comment by nimradium** [comment]
> it wasn't disabled in the old page.. you can see them by opening this in mobile view https://vsvipul.github.io/Rann-Neeti-2018/team.html and clicking on the top left button which opens up the categories.. You can try implementing the same in the new page too.. :)

oh I haven't noticed that, but I'm going to display the categories in the mobile version like in the desktop version because there is already a menu and I'm going to worry about that later.

**Comment by nimradium** [comment]
okay I added the categories in the mobile version 👍

**Comment by vsvipul** [comment]
> okay I added the categories in the mobile version

doesn't look that compact.. but i'll still merge it.. Try making it the way it was before, if possible.. Also, open up issues of all the above issues which are yet to be implemented, if you can.. i'll proceed to merge this to master ... fixes #3

**Comment by nimradium** [comment]
> doesn't look that compact.. but i'll still merge it.. Try making it the way it was before, if possible.. Also, open up issues of all the above issues which are yet to be implemented, if you can.. i'll proceed to merge this to master ... fixes #3

Gonna do this during the next days

**Pull request merged**
